quarkus.lambda.handler=notificarItemCritico
sqs.queue.url=https://sqs.us-east-2.amazonaws.com/986119050927/feedback-post

quarkus.index-dependency.infra-sqs.group-id=br.com.luizen
quarkus.index-dependency.infra-sqs.artifact-id=infra-sqs
