quarkus.lambda.handler=postarFeedback
sqs.queue.url=${SQS_QUEUE_URL}
dynamodb.tabela.feedbacks=${DYNAMODB_TABLE_FEEDBACKS}
aws.region=${AWS_REGION}

quarkus.index-dependency.infra-sqs.group-id=br.com.luizen
quarkus.index-dependency.infra-sqs.artifact-id=infra-sqs
quarkus.index-dependency.infra-dynamodb.group-id=br.com.luizen
quarkus.index-dependency.infra-dynamodb.artifact-id=infra-dynamodb
